### ISSUE TITLE
Can't accept the "Connect Banner" on the command line.

### ISSUE THREAD

**Issue by jmackie** [openconnect/openconnect#1]
I'm trying to connect to our Cisco SSL VPN at work via `openconnect`, but can't seem to get past the final stage when I'm asked to accept the T&Cs in a "Connect Banner". 

Here's the command and what I'm seeing

```
jmackie@nixos $ sudo openconnect --authgroup [GROUP] --user [USERNAME] [URL]
POST [URL]
Connected to [IP ADDRESS]
SSL negotiation with [URL]
Connected to HTTPS on [URL]
XML POST enabled
Please enter your username and password.
POST [URL]
XML POST enabled
Please enter your username and password.
Password:
POST [URL]
Got CONNECT response: HTTP/1.1 200 OK
CSTP connected. DPD 30, Keepalive 20
Connected as [ANOTHER IP ADDRESS], using SSL + lzs
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS0.9)-(DHE-CUSTOM4294967237)-(AES-256-CBC)-(SHA1).
DTLS connection compression using LZS.
Connect Banner:
| Your access to the ...
| ...blah blah blah
| You must accept this Agreement each time you use the Service and it is your responsibility to review it for any changes each time.
| More boring legal stuff
| Don't do illegal things
| ...blah blah blah
```

At which point it hangs as if waiting for stdin, but nothing I type has any effect.

```
jmackie@nixos $ openconnect --version
OpenConnect version v7.08
Using GnuTLS. Features present: RSA software token, HOTP software token, TOTP software token, System keys, DTLS
```

Running NixOS (18.09pre142796.4b649a99d84) and XMonad (0.13) so in need of a terminal-only solution.

**Comment by ngspinu** [comment]
Still going through this. Any fix yet? THanks!

**Comment by cernekee** [comment]
```
CSTP connected. DPD 30, Keepalive 20
Connected as [ANOTHER IP ADDRESS], using SSL + lzs
Established DTLS connection (using GnuTLS). Ciphersuite (DTLS0.9)-(DHE-CUSTOM4294967237)-(AES-256-CBC)-(SHA1).
DTLS connection compression using LZS.
```

This indicates that the client is in the mainloop and should be passing traffic.  It's not looking for any more user input at this point.  Last I checked, the CLI client doesn't require users to acknowledge the connect banner.

Is there a tun0 device in `ifconfig`?  Does it have an IP + routes configured?  openconnect should create tun0 and vpnc-script should set up the IP configuration.

**Comment by Panda-3** [comment]
Hi is there any fix to this? It wants me to accept before allowing me to continue. I am constantly getting the following error after.
`DTLS handshake failed: Resource temporarily unavailable, try again.`

**Comment by CatalinManolescu** [comment]
Any updates on this? Any idea on how to accept the agreement ?

**Comment by ngspinu** [comment]
```
#!/bin/bash
VPN_SERVER_ADDRESS='SOME.IP.ADRESS'
USER='jon.doe@vpn.org'
SERVER_CERT='sha256:some_random_key'


function checkTunnel {
	if [ "0" == `ifconfig | grep tun0 | wc -l` ];
	then
		return 1
	else
		return 0
	fi
}

checkTunnel
TUNNEL_UP=$?


if [[ $TUNNEL_UP -ne 0 ]]
then
	/sbin/ifconfig | grep DEVICE_NAME > /dev/null
	if [ $? -ne 0 ]; then
		sudo openconnect -b -q $VPN_SERVER_ADDRESS -u $USER --passwd-on-stdin < /path/to/text/fileContainingThePassword.txt --servercert $SERVER_CERT --reconnect-timeout 300

else
	else echo "already connected"
fi
```

**Comment by nmav** [comment]
This is a mirror of the repository. Please use the issue tracker at https://gitlab.com/openconnect/openconnect/issues/
