### ISSUE TITLE
Cross-compiling windows binary on Linux Mint 19.1 (Ubuntu 18.04)

### ISSUE THREAD

**Issue by vivin** [openconnect/openconnect#12]
I'm trying to build a Windows binary for version 8.04. Are there any instructions on how this can be done? I saw some old instructions on the [mailing list](http://lists.infradead.org/pipermail/openconnect-devel/2014-March/001728.html), but those don't seem to work.

I checked out the code, then ran `./autogen.sh` and then `./configure PKG_CONFIG_PATH="/usr/lib/x86_64-linux-gnu/pkgconfig/" --host=i686-w64-mingw32`. I had to explicitly specify `PKG_CONFIG_PATH` because otherwise it wasn't picking up that GnuTLS and OpenSSL were available.

Then `make check` failed with:

```
  CC       openconnect-xml.o
In file included from /usr/include/libxml2/libxml/parser.h:810:0,
                 from xml.c:27:
/usr/include/libxml2/libxml/encoding.h:28:10: fatal error: iconv.h: No such file or directory
 #include <iconv.h>
          ^~~~~~~~~
compilation terminated.
Makefile:1274: recipe for target 'openconnect-xml.o' failed
make: *** [openconnect-xml.o] Error 1
```
I was able to fix this by installing the `win-iconv-mingw-w64-dev` package. After this the build proceeded some more, but then failed with:

```
  CC       openconnect-xml.o
In file included from /usr/include/libxml2/libxml/parser.h:810:0,
                 from xml.c:27:
/usr/include/libxml2/libxml/encoding.h:31:10: fatal error: unicode/ucnv.h: No such file or directory
 #include <unicode/ucnv.h>
          ^~~~~~~~~~~~~~~~
compilation terminated.
Makefile:1274: recipe for target 'openconnect-xml.o' failed
make: *** [openconnect-xml.o] Error 1
```

This is as far as I got. `ucnv.h` exists in `/usr/include/unicode`, so I am not sure why it is complaining.

**Comment by nmav** [comment]
This is a mirror of the repository. Please use the issue tracker at https://gitlab.com/openconnect/openconnect/issues/
