### ISSUE TITLE
Cant get DTLS Cypher after log error

### ISSUE THREAD

**Issue by konsultaner** [openconnect/openconnect#4]
I cannot connect to my host. I only see this error. Maybe it has something tot with it?

`2019-04-05 15:23:21 | 3cd0 | Could not open C:/Users/Richard Burkhardt/AppData/Local/Temp\vpnc.log: 5`

Maybe because my home folder is `C:/Users/Richard Burkhardt/` with a space in it?

I'm on a Win10 64bit

This is my VPN Info:

![image](https://user-images.githubusercontent.com/2699538/55632209-1b982480-57ba-11e9-8ab3-e64d11ce7f9f.png)

The log keeps doing this:

![image](https://user-images.githubusercontent.com/2699538/55632269-3b2f4d00-57ba-11e9-8a46-3efa695aa59a.png)

**Comment by nmav** [comment]
This is a mirror of the repository. Please use the issue tracker at https://gitlab.com/openconnect/openconnect/issues/
