### ISSUE TITLE
How to enter two password?

### ISSUE THREAD

**Issue by holms** [openconnect/openconnect#5]
This is required for 2FA. I'm trying to connect to a vpn with openconnect from CLI. According to [this](https://crashcourse.housegordon.org/OpenConnect.html) page openconnect should ask for password. It doesn't ask anything in my case. I've tried to enter it from stdin and pass a username parameter, but I need a place to enter 2FA pin. How can I achieve this?

**Comment by nmav** [comment]
This is a mirror of the repository. Please use the issue tracker at https://gitlab.com/openconnect/openconnect/issues/
