### ISSUE TITLE
doesn't work for palo alto

### ISSUE THREAD

**Issue by codeman101** [openconnect/openconnect#8]
I can't get it to work with globalconnect. The cloest I got was with this command from the archwiki on it `# openconnect -u user --passwd-on-stdin vpnserver` but when I run that using my actual vpnserver it just hangs. I think it might be because it's not set to the right vpn type but when I run `openconnect --protocol=gp` it just gives me the help menu. Also when I run `openconnect --protocol=gp -u user --passwd-on-stdin vpnserver` it still hangs.

By the way you should added a section in the help menu as to how arguments go because like I said I had to use the archwiki which got me closer that the manual on the openconnect website that the help menu has a link for.

**Comment by codeman101** [comment]
It might also be failing because of SNAIL authentication. I heard that type of authentication hasn't been implemented in the official Linux version that GlobalProtect made. Maybe you can beat them to it. :)

**Comment by nmav** [comment]
This is a mirror of the repository. Please use the issue tracker at https://gitlab.com/openconnect/openconnect/issues/
