### ISSUE TITLE
Verification of CA-File does not produce Warning / Error

### ISSUE THREAD

**Issue by thedachs** [openconnect/openconnect#9]
Hi there,

we recently changed the certificate at our Cisco ASA. This included a change of our CA.
We told our customers to configure openconnect to check the CA certificate when connecting to our vpn gateway.
Now the weird thing is: 
Configurations using the old CA did not produce any warning or error after we changed the certificate chain at the gateway.
This is reproducible by authenticating to the gateway using a CA file that is NOT our CA (e.g. Amazon):

```
$ openconnect --authenticate <vpn-gateway-hostname> --cafile /etc/ssl/certs/Amazon_Root_CA_1.pem --verbose
POST https://<vpn-gateway-hostname>/
Attempting to connect to server <vpn-gateway-ip>:443
Connected to <vpn-gateway-ip>:443
SSL negotiation with <vpn-gateway-hostname>
Connected to HTTPS on <vpn-gateway-hostname>
Got HTTP response: HTTP/1.1 200 OK
Content-Type: text/html; charset=utf-8
Transfer-Encoding: chunked
Cache-Control: no-cache
Pragma: no-cache
Connection: Keep-Alive
Date: Wed, 29 May 2019 09:39:53 GMT
X-Frame-Options: SAMEORIGIN
X-Aggregate-Auth: 1
HTTP body chunked (-2)
XML POST enabled
Please enter your username and password.
```

The certificate and chain provided by our gateway is valid indeed (the CA is a trusted CA listed in /etc/ssl/certs), so of course the validation should not fail at all. But it is not checked against the specific CA file provided by --cafile. 
[networkmanager-openconnect produces the same behaviour - the CA chosen there is also not checked].

I think at least some kind of warning should be raised - the option to specify a particular CA file is a security feature, so that only certs issued by this particular CA should be accepted by the client without any warnings.

Tested with:
OpenConnect Version v8.03 (Arch Linux)
OpenConnect version v7.08-3ubuntu0.18.04.1 (Ubuntu 18.04)

Best regards and thanks for your great work!

**Comment by nmav** [comment]
This is a mirror of the repository. Please use the issue tracker at https://gitlab.com/openconnect/openconnect/issues/
